# Specify to use node
language: node_js
# Specify the node versions to run on
node_js:
  - "6.9"
  - "node"

# Set up environment variables for tests
env:
  global:
  
# Make sure to have typings before the test
before_script:
#  - npm run typings
# Make sure to bundle the application before any deploys
before_deploy:
#  - npm run bundle
# Report code coverage to coveralls after successful test runs
after_success:
#  - npm run coveralls
# Do not send build notifications
notifications:
  email: true