# Specify to use node
language: node_js
# Specify the node versions to run on
node_js:
  - "stable"

# Set up environment variables for tests
env:
  global:
  
# Make sure to have typings before the test
before_script:
#  - npm run typings
# Report code coverage to coveralls after successful test runs
after_success:
    - npm run coverage
    - npm run report-coverage
    
# Make sure to bundle the application before any deploys
before_deploy:
    - npm i -g typescript rimraf
    
# Deploy
deploy:
  - provider: npm
    email: stephane@dfordev.com
    api_key: $NPM_TOKEN
    on:
        branch: "master"
    tag: latest
  - provider: npm
    email: stephane@dfordev.com
    api_key: $NPM_TOKEN
    on:
        branch: "develop"
    tag: snapshot
#   - provider: npm
#     email: stephane@dfordev.com
#     api_key: $NPM_TOKEN
#     on:
#         all_branches: true
#         branch: "develop"
    
# Do not send build notifications
notifications:
  email: true