# Specify to use node
language: node_js
# Specify the node versions to run on
node_js:
  - "stable"

# Set up environment variables for tests
env:
  global:
  
# Make sure to have typings before the test
before_script:
#  - npm run typings
# Make sure to bundle the application before any deploys
before_deploy:
  - npm install rimraf
#  - npm run bundle
# Report code coverage to coveralls after successful test runs
after_success:
    - npm run coverage
    - npm run report-coverage
    
# Deploy
deploy:
  provider: npm
  email: stephane@dfordev.com
  api_key: $NPM_TOKEN
  on:
    tags: true # Only deploy on tag commits (git push --tags to ensue tags are uploaded to remote)
    branch: "master"
    
# Do not send build notifications
notifications:
  email: true